import { test, expect } from "@playwright/test";
import { serve, noSidewaysScroll } from "./demo.mjs";

test("Cross Sums totals, keyboard entry, pencil, undo, hint, appearance, language and saved progress", async ({ page }) => {
  const errors = [];
  page.on("pageerror", error => errors.push(String(error)));
  await serve(page);
  await page.goto("http://kazu.test/cross-sums.html?seed=42");
  await expect(page.locator(".kk-cell")).toHaveCount(100);
  const active = page.locator(".kk-cell:not(:disabled)").first();
  await active.focus();
  await page.keyboard.press("p");
  await page.keyboard.press("3");
  await expect(page.locator(".kk-board svg")).toContainText("3");
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await page.getByRole("button", { name: "Pencil marks", exact: true }).click();
  await active.focus();
  await page.keyboard.press("4");
  await expect(page.locator(".kk-board svg")).toContainText("4");
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await active.click();
  await page.getByRole("button", { name: "5", exact: true }).click();
  await expect(page.locator(".kk-board svg")).toContainText("5");
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await page.getByRole("button", { name: "Hint", exact: true }).click();
  await expect(page.getByRole("status").last()).toContainText("Row");
  await page.locator("#material").selectOption("slate");
  await page.locator("#pieces").selectOption("tiles");
  await page.getByRole("button", { name: "日本語", exact: true }).click();
  await expect(page.getByRole("button", { name: "戻す", exact: true })).toBeVisible();
  await noSidewaysScroll(page);
  await page.goto("http://kazu.test/cross-sums.html");
  await expect(page.locator(".kk-cell:not(:disabled)").filter({ has: page.locator("text=1") })).toHaveCount(0);
  await expect(page.locator(".kk-board svg text")).not.toHaveCount(0);
  expect(errors).toEqual([]);
});
