import type { AkariLanguage } from "./akari-play.types.ts";

export const AKARI_STRINGS = {
  en: {
    title: "Akari",
    help: "Place bulbs on white squares. Each bulb lights along its row and column until a black square or the edge. Light every white square; bulbs cannot see one another. Numbered black squares touch exactly that many bulbs. Click, tap or press Enter or Space to toggle a bulb; arrows move; Delete removes it.",
    undo: "Undo",
    hint: "Hint",
    check: "Check",
    restart: "Restart",
    expand: "Just the board",
    close: "Close",
    won: "Every square is lit. Solved!",
    helped: "Solved with help.",
    checked: "No rule conflicts so far. Keep lighting the board.",
    wrong: "Check the dark squares, bulb lines and numbered squares.",
    hintWhy: "A bulb from the only proved solution was placed.",
    noHint: "No proved hint is available.",
    row: "Row",
    column: "column",
    white: "white square",
    bulb: "bulb",
    lit: "lit",
    dark: "dark",
    black: "black square",
    clue: "number",
  },
  ja: {
    title: "美術館",
    help: "白マスに電球を置きます。電球は黒マスか盤の端まで、縦横に光ります。白マスすべてを照らし、電球同士が見えないようにします。数字のある黒マスには、その数だけ電球を隣接させます。タップ、クリック、Enter、Spaceで電球を切り替えます。矢印キーで移動し、Deleteで消します。",
    undo: "戻す",
    hint: "ヒント",
    check: "確かめる",
    restart: "やり直す",
    expand: "盤だけ",
    close: "閉じる",
    won: "全部照らしました。完成！",
    helped: "ヒントを使って完成！",
    checked: "ここまでルールに合っています。残りも照らしましょう。",
    wrong: "暗いマス、電球の見通し、数字のマスを確かめましょう。",
    hintWhy: "唯一の解答で必要な電球を置きました。",
    noHint: "確かなヒントがありません。",
    row: "行",
    column: "列",
    white: "白マス",
    bulb: "電球",
    lit: "照明あり",
    dark: "暗い",
    black: "黒マス",
    clue: "数字",
  },
} as const;

export function akariWords(language: AkariLanguage = "en") {
  return AKARI_STRINGS[language];
}
